// ─── Color math + accessibility utilities ──────────────────────────────────
// Pure functions, no dependencies. Shared by lib/themes.js (preset generation)
// and ThemeContext (custom color handling) so there's exactly one place that
// knows how to turn a single hex color into hover/soft/foreground variants.

export function hexToRgb(hex) {
  const clean = hex.replace("#", "");
  const full = clean.length === 3
    ? clean.split("").map((c) => c + c).join("")
    : clean;
  return {
    r: parseInt(full.slice(0, 2), 16),
    g: parseInt(full.slice(2, 4), 16),
    b: parseInt(full.slice(4, 6), 16),
  };
}

export function rgbToHex(r, g, b) {
  const c = (n) => Math.round(Math.min(255, Math.max(0, n))).toString(16).padStart(2, "0");
  return `#${c(r)}${c(g)}${c(b)}`;
}

export function hexToHsl(hex) {
  const { r, g, b } = hexToRgb(hex);
  const rn = r / 255, gn = g / 255, bn = b / 255;
  const max = Math.max(rn, gn, bn), min = Math.min(rn, gn, bn);
  let h = 0, s = 0;
  const l = (max + min) / 2;
  if (max !== min) {
    const d = max - min;
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
    switch (max) {
      case rn: h = ((gn - bn) / d + (gn < bn ? 6 : 0)) / 6; break;
      case gn: h = ((bn - rn) / d + 2) / 6; break;
      case bn: h = ((rn - gn) / d + 4) / 6; break;
    }
  }
  return [h * 360, s * 100, l * 100];
}

export function hslToHex(h, s, l) {
  s /= 100; l /= 100;
  const a = s * Math.min(l, 1 - l);
  const f = (n) => {
    const k = (n + h / 30) % 12;
    const color = l - a * Math.max(Math.min(k - 3, 9 - k, 1), -1);
    return Math.round(255 * color).toString(16).padStart(2, "0");
  };
  return `#${f(0)}${f(8)}${f(4)}`;
}

// WCAG relative luminance — used for contrast ratio + readable foreground.
export function relativeLuminance(hex) {
  const { r, g, b } = hexToRgb(hex);
  const chan = (v) => {
    const c = v / 255;
    return c <= 0.03928 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4);
  };
  return 0.2126 * chan(r) + 0.7152 * chan(g) + 0.0722 * chan(b);
}

// WCAG contrast ratio between two hex colors (1–21).
export function contrastRatio(hexA, hexB) {
  const l1 = relativeLuminance(hexA) + 0.05;
  const l2 = relativeLuminance(hexB) + 0.05;
  return l1 > l2 ? l1 / l2 : l2 / l1;
}

// Picks black or white — whichever gives better contrast against `hex`.
// Used so a primary/secondary/accent button's text stays readable no matter
// how light or dark the user's chosen color is.
export function getReadableForeground(hex) {
  const whiteContrast = contrastRatio(hex, "#FFFFFF");
  const blackContrast = contrastRatio(hex, "#000000");
  return whiteContrast >= blackContrast ? "#FFFFFF" : "#0A0A0F";
}

// Darkens/lightens a hex color by shifting HSL lightness — used for hover states.
export function shiftLightness(hex, deltaPct) {
  const [h, s, l] = hexToHsl(hex);
  return hslToHex(h, s, Math.min(100, Math.max(0, l + deltaPct)));
}

// A translucent rgba() version of a color — used for soft backgrounds/glows.
export function withAlpha(hex, alpha) {
  const { r, g, b } = hexToRgb(hex);
  return `rgba(${r},${g},${b},${alpha})`;
}

// Linear RGB interpolation between two hex colors — a same-math JS
// equivalent of CSS color-mix(in srgb, ...), so the pre-hydration boot
// script (plain JS, no CSS parsing) and the runtime provider always agree
// pixel-for-pixel. `weightPct` is how much of `hexA` to mix in (0–100).
export function mixHex(hexA, hexB, weightPct) {
  const a = hexToRgb(hexA), b = hexToRgb(hexB);
  const t = weightPct / 100;
  return rgbToHex(
    a.r * t + b.r * (1 - t),
    a.g * t + b.g * (1 - t),
    a.b * t + b.b * (1 - t)
  );
}

// Full derived token set for one base color (primary/secondary/accent all
// use this shape). `mode` nudges hover direction — hover darkens in light
// mode (more "pressed") and lightens in dark mode (more "lit up").
export function deriveColorTokens(hex, mode = "light") {
  const hoverDelta = mode === "dark" ? 8 : -8;
  return {
    base: hex,
    hover: shiftLightness(hex, hoverDelta),
    active: shiftLightness(hex, hoverDelta * 1.6),
    soft: withAlpha(hex, mode === "dark" ? 0.16 : 0.09),
    softHover: withAlpha(hex, mode === "dark" ? 0.24 : 0.14),
    glow: withAlpha(hex, 0.28),
    foreground: getReadableForeground(hex),
  };
}

// 50–900 shade scale conceptually requested by the spec — generated by
// walking lightness from ~97% (50) down to ~12% (900) while keeping hue/sat,
// so any of the three brand colors gets a full Tailwind-shaped ramp on demand
// (e.g. for one-off chart ticks) without hand-authoring 9 stops per color.
const SHADE_LIGHTNESS = { 50: 97, 100: 93, 200: 85, 300: 74, 400: 62, 500: 50, 600: 42, 700: 34, 800: 26, 900: 16 };
export function generateShadeScale(hex) {
  const [h, s] = hexToHsl(hex);
  const scale = {};
  for (const [step, l] of Object.entries(SHADE_LIGHTNESS)) {
    scale[step] = hslToHex(h, Math.min(100, s), l);
  }
  return scale;
}
