export const CONTENT_ITEMS = [
  {
    id: 1,
    title: "Next.js 16 Breaking Changes You Need to Know",
    type: "video",
    platform: "YouTube",
    platforms: ["YouTube"],
    status: "Published",
    thumbnail: "https://picsum.photos/seed/creator1/400/225",
    views: "128K",
    engagement: "8.4%",
    date: "2 days ago",
    tags: ["Next.js", "Web Dev"],
    duration: "18:42",
    category: "Tutorial",
  },
  {
    id: 2,
    title: "I Built a Full SaaS in 48 Hours",
    type: "video",
    platform: "YouTube",
    platforms: ["YouTube"],
    status: "Published",
    thumbnail: "https://picsum.photos/seed/creator2/400/225",
    views: "74K",
    engagement: "11.2%",
    date: "1 week ago",
    tags: ["SaaS", "Build", "AI"],
    duration: "28:15",
    category: "Build",
  },
  {
    id: 3,
    title: "Morning Routine That Changed My Output",
    type: "short",
    platform: "TikTok",
    platforms: ["TikTok"],
    status: "Published",
    thumbnail: "https://picsum.photos/seed/creator3/400/225",
    views: "512K",
    engagement: "19.3%",
    date: "3 days ago",
    tags: ["Lifestyle", "Productivity"],
    duration: "0:58",
    category: "Vlog",
  },
  {
    id: 4,
    title: "Tailwind CSS 4 — Everything That Changed",
    type: "video",
    platform: "YouTube",
    platforms: ["YouTube"],
    status: "Draft",
    thumbnail: "https://picsum.photos/seed/creator4/400/225",
    views: "-",
    engagement: "-",
    date: "Just now",
    tags: ["CSS", "Design", "Frontend"],
    duration: "14:08",
    category: "Tutorial",
  },
  {
    id: 5,
    title: "How I Eat High Protein on $60 a Week",
    type: "article",
    platform: "Newsletter",
    platforms: ["Newsletter"],
    status: "Published",
    thumbnail: "https://picsum.photos/seed/creator5/400/225",
    views: "22K",
    engagement: "6.1%",
    date: "4 days ago",
    tags: ["Fitness", "Nutrition"],
    duration: "9 min read",
    category: "Health",
  },
  {
    id: 6,
    title: "Solo Travel Japan on $50 a Day",
    type: "video",
    platform: "YouTube",
    platforms: ["YouTube"],
    status: "Published",
    thumbnail: "https://picsum.photos/seed/creator6/400/225",
    views: "245K",
    engagement: "13.7%",
    date: "2 weeks ago",
    tags: ["Travel", "Japan", "Budget"],
    duration: "22:30",
    category: "Travel",
  },
  {
    id: 7,
    title: "5 Passive Income Streams I Actually Use",
    type: "video",
    platform: "YouTube",
    platforms: ["YouTube"],
    status: "Scheduled",
    thumbnail: "https://picsum.photos/seed/creator7/400/225",
    views: "-",
    engagement: "-",
    date: "Scheduled for tomorrow",
    tags: ["Finance", "Passive Income"],
    duration: "16:55",
    category: "Business",
  },
  {
    id: 8,
    title: "My Honest Thoughts on React 19",
    type: "podcast",
    platform: "Podcast",
    platforms: ["Podcast"],
    status: "Published",
    thumbnail: "https://picsum.photos/seed/creator8/400/225",
    views: "18K",
    engagement: "7.9%",
    date: "5 days ago",
    tags: ["React", "Web Dev"],
    duration: "42 min",
    category: "Tech Talk",
  },
  {
    id: 9,
    title: "The 5 AM Gym Routine I've Kept for 1 Year",
    type: "short",
    platform: "Instagram",
    platforms: ["Instagram Reels"],
    status: "Published",
    thumbnail: "https://picsum.photos/seed/creator9/400/225",
    views: "330K",
    engagement: "14.5%",
    date: "1 week ago",
    tags: ["Fitness", "Routine"],
    duration: "0:45",
    category: "Health",
  },
  {
    id: 10,
    title: "How I Made $8,400 From One Newsletter Issue",
    type: "article",
    platform: "Newsletter",
    platforms: ["Newsletter"],
    status: "Published",
    thumbnail: "https://picsum.photos/seed/creator10/400/225",
    views: "41K",
    engagement: "9.8%",
    date: "3 weeks ago",
    tags: ["Newsletter", "Business"],
    duration: "12 min read",
    category: "Business",
  },
  {
    id: 11,
    title: "Replying to Your Hardest Dev Questions",
    type: "short",
    platform: "TikTok",
    platforms: ["TikTok"],
    status: "Draft",
    thumbnail: "https://picsum.photos/seed/creator11/400/225",
    views: "-",
    engagement: "-",
    date: "Yesterday",
    tags: ["Q&A", "Dev"],
    duration: "0:52",
    category: "Community",
  },
  {
    id: 12,
    title: "I Tried Every AI Code Editor — Here's the Verdict",
    type: "video",
    platform: "YouTube",
    platforms: ["YouTube"],
    status: "Published",
    thumbnail: "https://picsum.photos/seed/creator12/400/225",
    views: "98K",
    engagement: "10.2%",
    date: "1 month ago",
    tags: ["AI", "Tools", "Dev"],
    duration: "24:17",
    category: "Review",
  },
  {
    id: 13,
    title: "Budget Meal Prep for the Whole Week",
    type: "short",
    platform: "Instagram",
    platforms: ["Instagram Reels"],
    status: "Published",
    thumbnail: "https://picsum.photos/seed/creator13/400/225",
    views: "178K",
    engagement: "16.1%",
    date: "2 weeks ago",
    tags: ["Cooking", "Budget"],
    duration: "0:60",
    category: "Cooking",
  },
  {
    id: 14,
    title: "Building a Second Brain with Obsidian in 2025",
    type: "article",
    platform: "Newsletter",
    platforms: ["Newsletter"],
    status: "Scheduled",
    thumbnail: "https://picsum.photos/seed/creator14/400/225",
    views: "-",
    engagement: "-",
    date: "Scheduled for next Monday",
    tags: ["Productivity", "PKM"],
    duration: "15 min read",
    category: "Productivity",
  },
  {
    id: 15,
    title: "From Zero to $10K MRR: The Full Story",
    type: "podcast",
    platform: "Podcast",
    platforms: ["Podcast"],
    status: "Published",
    thumbnail: "https://picsum.photos/seed/creator15/400/225",
    views: "31K",
    engagement: "8.8%",
    date: "2 months ago",
    tags: ["SaaS", "Founder", "Business"],
    duration: "58 min",
    category: "Business",
  },
  {
    id: 16,
    title: "A Week Working From Bali — Honest Thoughts",
    type: "video",
    platform: "YouTube",
    platforms: ["YouTube"],
    status: "Published",
    thumbnail: "https://picsum.photos/seed/creator16/400/225",
    views: "62K",
    engagement: "9.5%",
    date: "3 weeks ago",
    tags: ["Travel", "Remote Work", "Vlog"],
    duration: "20:04",
    category: "Travel",
  },
];

// ISO dates spread over the last 60 days
function daysAgo(n) {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString();
}

export const MOCK_CONTENT = [
  {
    id: "mock-1",
    title: "Next.js 16 Breaking Changes You Need to Know",
    type: "video",
    platforms: ["YouTube"],
    status: "published",
    description: "A deep-dive into the breaking changes introduced in Next.js 16 and how to migrate your existing projects.",
    tags: ["Next.js", "Web Dev"],
    createdAt: daysAgo(2),
    thumbnail: { youtube: "https://picsum.photos/seed/creator1/400/225" },
  },
  {
    id: "mock-2",
    title: "I Built a Full SaaS in 48 Hours",
    type: "video",
    platforms: ["YouTube"],
    status: "published",
    description: "A full walkthrough of building and launching a SaaS product over a single weekend using AI tools.",
    tags: ["SaaS", "Build", "AI"],
    createdAt: daysAgo(7),
    thumbnail: { youtube: "https://picsum.photos/seed/creator2/400/225" },
  },
  {
    id: "mock-3",
    title: "Morning Routine That Changed My Output",
    type: "short",
    platforms: ["TikTok"],
    status: "published",
    description: "The exact morning routine I've been following for 6 months that doubled my creative output.",
    tags: ["Lifestyle", "Productivity"],
    createdAt: daysAgo(3),
    thumbnail: { instagram: "https://picsum.photos/seed/creator3/400/225" },
  },
  {
    id: "mock-4",
    title: "Tailwind CSS 4 — Everything That Changed",
    type: "video",
    platforms: ["YouTube"],
    status: "draft",
    description: "A comprehensive look at Tailwind CSS 4's new features and what it means for your workflow.",
    tags: ["CSS", "Design", "Frontend"],
    createdAt: daysAgo(1),
    thumbnail: { youtube: "https://picsum.photos/seed/creator4/400/225" },
  },
  {
    id: "mock-5",
    title: "How I Eat High Protein on $60 a Week",
    type: "article",
    platforms: ["Newsletter"],
    status: "published",
    description: "My complete grocery strategy for hitting 180g of protein daily while keeping costs under $60 per week.",
    tags: ["Fitness", "Nutrition"],
    createdAt: daysAgo(4),
    thumbnail: { instagram: "https://picsum.photos/seed/creator5/400/225" },
  },
  {
    id: "mock-6",
    title: "Solo Travel Japan on $50 a Day",
    type: "video",
    platforms: ["YouTube"],
    status: "published",
    description: "Everything you need to know to travel Japan solo on a tight budget — accommodation, food, and transport.",
    tags: ["Travel", "Japan", "Budget"],
    createdAt: daysAgo(14),
    thumbnail: { youtube: "https://picsum.photos/seed/creator6/400/225" },
  },
  {
    id: "mock-7",
    title: "5 Passive Income Streams I Actually Use",
    type: "video",
    platforms: ["YouTube"],
    status: "scheduled",
    description: "A transparent breakdown of the 5 income streams that now generate revenue while I sleep.",
    tags: ["Finance", "Passive Income"],
    createdAt: daysAgo(5),
    thumbnail: { youtube: "https://picsum.photos/seed/creator7/400/225" },
  },
  {
    id: "mock-8",
    title: "My Honest Thoughts on React 19",
    type: "podcast",
    platforms: ["Podcast"],
    status: "published",
    description: "A candid discussion on React 19's new features, what works, what doesn't, and where the ecosystem is headed.",
    tags: ["React", "Web Dev"],
    createdAt: daysAgo(5),
    thumbnail: { instagram: "https://picsum.photos/seed/creator8/400/225" },
  },
  {
    id: "mock-9",
    title: "The 5 AM Gym Routine I've Kept for 1 Year",
    type: "short",
    platforms: ["Instagram Reels"],
    status: "published",
    description: "The morning gym routine I've been consistent with for an entire year and the results it's produced.",
    tags: ["Fitness", "Routine"],
    createdAt: daysAgo(7),
    thumbnail: { instagram: "https://picsum.photos/seed/creator9/400/225" },
  },
  {
    id: "mock-10",
    title: "How I Made $8,400 From One Newsletter Issue",
    type: "article",
    platforms: ["Newsletter"],
    status: "published",
    description: "The exact breakdown of one newsletter issue that generated $8,400 in revenue from a single send.",
    tags: ["Newsletter", "Business"],
    createdAt: daysAgo(21),
    thumbnail: { instagram: "https://picsum.photos/seed/creator10/400/225" },
  },
  {
    id: "mock-11",
    title: "Replying to Your Hardest Dev Questions",
    type: "short",
    platforms: ["TikTok"],
    status: "draft",
    description: "Answering the most technical and tricky developer questions submitted by the community.",
    tags: ["Q&A", "Dev"],
    createdAt: daysAgo(1),
    thumbnail: { instagram: "https://picsum.photos/seed/creator11/400/225" },
  },
  {
    id: "mock-12",
    title: "I Tried Every AI Code Editor — Here's the Verdict",
    type: "video",
    platforms: ["YouTube"],
    status: "published",
    description: "After 30 days testing Cursor, Windsurf, Copilot, and more — here's which AI code editor I actually recommend.",
    tags: ["AI", "Tools", "Dev"],
    createdAt: daysAgo(30),
    thumbnail: { youtube: "https://picsum.photos/seed/creator12/400/225" },
  },
  {
    id: "mock-13",
    title: "Budget Meal Prep for the Whole Week",
    type: "short",
    platforms: ["Instagram Reels"],
    status: "published",
    description: "A full week of nutritious meals prepped in under 2 hours for less than $40.",
    tags: ["Cooking", "Budget"],
    createdAt: daysAgo(14),
    thumbnail: { instagram: "https://picsum.photos/seed/creator13/400/225" },
  },
  {
    id: "mock-14",
    title: "Building a Second Brain with Obsidian in 2025",
    type: "article",
    platforms: ["Newsletter"],
    status: "scheduled",
    description: "My updated system for capturing, connecting, and surfacing ideas using Obsidian's latest features.",
    tags: ["Productivity", "PKM"],
    createdAt: daysAgo(8),
    thumbnail: { instagram: "https://picsum.photos/seed/creator14/400/225" },
  },
  {
    id: "mock-15",
    title: "From Zero to $10K MRR: The Full Story",
    type: "podcast",
    platforms: ["Podcast"],
    status: "published",
    description: "The unfiltered story of how I grew my SaaS from the first paying customer to $10K monthly recurring revenue.",
    tags: ["SaaS", "Founder", "Business"],
    createdAt: daysAgo(60),
    thumbnail: { instagram: "https://picsum.photos/seed/creator15/400/225" },
  },
  {
    id: "mock-16",
    title: "A Week Working From Bali — Honest Thoughts",
    type: "video",
    platforms: ["YouTube"],
    status: "published",
    description: "An honest vlog about remote working from Bali for a week — the good, the bad, and the hidden costs.",
    tags: ["Travel", "Remote Work", "Vlog"],
    createdAt: daysAgo(21),
    thumbnail: { youtube: "https://picsum.photos/seed/creator16/400/225" },
  },
];

export const ROADMAP_ITEMS = [
  { id: 1, title: "AI SaaS Idea", status: "Brainstorming", tags: ["AI", "SaaS"], due: "Apr 25", priority: "High", progress: 0, checklist: [], notes: "", platforms: ["YouTube", "Twitter"], activity: [{ id: 1, text: "Created idea", date: "2 days ago" }] },
  { id: 2, title: "Q&A Session", status: "Brainstorming", tags: ["Community"], due: "Apr 28", priority: "Medium", progress: 20, checklist: [{ id: 1, text: "Collect questions", done: true }, { id: 2, text: "Draft answers", done: false }], notes: "Keep it under 10 mins.", platforms: ["YouTube"], activity: [{ id: 1, text: "Moved to Brainstorming", date: "1 day ago" }] },
  { id: 3, title: "Office Setup V2", status: "Brainstorming", tags: ["Vlog"], due: "May 2", priority: "Low", progress: 0, checklist: [], notes: "", platforms: ["YouTube", "Instagram"], activity: [{ id: 1, text: "Added to backlog", date: "1 week ago" }] },
  { id: 4, title: "Next.js 16 Deep Dive", status: "Scripting", tags: ["Tech"], due: "Apr 24", priority: "High", progress: 40, checklist: [{ id: 1, text: "Outline", done: true }, { id: 2, text: "First draft", done: false }], notes: "Highlight routing changes.", platforms: ["YouTube"], activity: [{ id: 1, text: "Moved to Scripting", date: "3 hours ago" }] },
  { id: 5, title: "Tailwind 4 vs 3", status: "Scripting", tags: ["Design"], due: "Apr 26", priority: "Medium", progress: 60, checklist: [{ id: 1, text: "Research features", done: true }, { id: 2, text: "Code examples", done: false }], notes: "", platforms: ["YouTube", "Twitter"], activity: [{ id: 1, text: "Checklist updated", date: "4 hours ago" }] },
  { id: 6, title: "State of React 2026", status: "Production", tags: ["Trends"], due: "Apr 30", priority: "Urgent", progress: 85, checklist: [{ id: 1, text: "Record A-roll", done: true }, { id: 2, text: "Record screen capture", done: true }, { id: 3, text: "Audio sync", done: false }], notes: "Use the new mic.", platforms: ["YouTube", "TikTok"], activity: [{ id: 1, text: "Moved to Production", date: "Yesterday" }] },
  { id: 7, title: "Editor Vlog #12", status: "Post-Production", tags: ["Behind the scenes"], due: "May 5", priority: "Low", progress: 95, checklist: [{ id: 1, text: "Color grade", done: true }, { id: 2, text: "Export", done: false }], notes: "", platforms: ["Instagram", "TikTok"], activity: [{ id: 1, text: "Moved to Post-Production", date: "Just now" }] },
];

export const COLUMNS = [
  { name: "Brainstorming", color: "text-purple-400", bg: "bg-purple-400/10", border: "border-purple-400/20" },
  { name: "Scripting", color: "text-blue-400", bg: "bg-blue-400/10", border: "border-blue-400/20" },
  { name: "Production", color: "text-amber-400", bg: "bg-amber-400/10", border: "border-amber-400/20" },
  { name: "Post-Production", color: "text-emerald-400", bg: "bg-emerald-400/10", border: "border-emerald-400/20" },
];

export const MEDIA_ASSETS = [
  { id: 1, name: "b-roll-coffee.mp4", type: "video", size: "12.4 MB", tags: ["vlog", "lifestyle"], color: "blue" },
  { id: 2, name: "thumbnail-bg.png", type: "image", size: "1.2 MB", tags: ["design", "gradient"], color: "purple" },
  { id: 3, name: "intro-music.wav", type: "audio", size: "4.5 MB", tags: ["audio", "upbeat"], color: "amber" },
  { id: 4, name: "logo-transparent.png", type: "image", size: "0.4 MB", tags: ["brand"], color: "emerald" },
  { id: 5, name: "setup-tour-raw.mov", type: "video", size: "1.2 GB", tags: ["raw"], color: "rose" },
  { id: 6, name: "interview-clip.mp4", type: "video", size: "45.2 MB", tags: ["interview"], color: "blue" },
  { id: 7, name: "background-texture.jpg", type: "image", size: "2.1 MB", tags: ["assets"], color: "purple" },
  { id: 8, name: "outro-theme.mp3", type: "audio", size: "3.2 MB", tags: ["audio"], color: "amber" },
  { id: 9, name: "overlay-particles.mov", type: "video", size: "89.4 MB", tags: ["vfx"], color: "blue" },
  { id: 10, name: "hero-shot.png", type: "image", size: "5.6 MB", tags: ["thumbnail"], color: "purple" },
];

export const SERIES_LOOKUP = {
  "1": { name: "Next.js Masterclass", type: "Course", episodes: 12, completed: 4, gradient: "from-indigo-500 to-purple-600" },
  "2": { name: "Daily Tech News", type: "Shorts", episodes: 30, completed: 18, gradient: "from-red-500 to-orange-500" },
  "3": { name: "Build a CMS with AI", type: "Project", episodes: 5, completed: 1, gradient: "from-emerald-500 to-teal-600" },
};
